In [2]:
# %load ml.py
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import linear_model
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

%config InlineBackend.figure_format='svg'
plt.rcParams['figure.dpi']=120

pd.options.display.float_format='{:,.2f}'.format
pd.set_option('display.max_colwidth', None)


In [4]:
df=pd.read_csv('./data/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
lr=linear_model.LinearRegression()

In [9]:
lr.fit(df.drop(['price'], axis=1), df['price'])

LinearRegression()

In [11]:
lr.coef_
lr.intercept_

lr.predict([[3200]])

array([135.78767123])

180616.43835616432

C:\Users\Kwang-Chul Kwon\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([615136.98630137])

### Save Model To a File Using Python Pickle

In [15]:
import pickle

with open('lr_pickle.pickle', 'wb') as file:
    pickle.dump(lr, file)

In [16]:
with open('lr_pickle.pickle', 'rb') as file:
    lr_=pickle.load(file)

In [17]:
lr_.coef_
lr_.intercept_
lr_.predict([[3200]])

array([135.78767123])

180616.43835616432

C:\Users\Kwang-Chul Kwon\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([615136.98630137])

### Save Trained Model Using joblib

In [20]:
import joblib

In [21]:
joblib.dump(lr, 'lr_joblib')

['lr_joblib']

In [23]:
lr_=joblib.load('lr_joblib')

In [25]:
lr_.coef_
lr_.intercept_
lr_.predict([[3200]])

array([135.78767123])

180616.43835616432

C:\Users\Kwang-Chul Kwon\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([615136.98630137])