In [1]:
# %load command1.py

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [2]:
import random

In [3]:
random.random() # Random float:  0.0 <= x < 1.0
random.uniform(2.5, 10.0)  # Random float: 2.5 <= x <10
random.expovariate(1/5) # Interval between arrivals averaging 5 seconds
random.randrange(10) # Integer from 0 to 9 inclusive
random.randrange(0, 101, 2) # Even integer from 0 to 100 inclusive 
random.choice(['win', 'lose', 'draw']) # Single random element from a sequence
deck='ace two thre four'.split()
random.shuffle(deck) # Shuffle a list
random.sample([10, 20, 30 , 40, 50], k=3) # random sample without replacement
random.choices([10, 20, 30, 40, 50], k=3) # random sample without replacement

0.9084632385914186

7.4167216387338435

5.8724147534484015

6

90

'win'

[40, 10, 30]

[30, 10, 30]

# random integer number
- Generate random numbers using randint() and randrange().

|Function|	Description|
|:--|:--|
|random.randint(0, 9)|	Returns any random integer from 0 to 9|
|random.randrange(2, 20, 2)|	Returns any random integer from 2 to 20 with step 2|
|random.randrange(100, 1000, 3)|	Returns any random integer of specific length 3|
|random.randrange(-50, -5)	|Returns any random negative integer between -50 to -6.|
|random.sample(range(0, 1000), 10)|	Returns a list of random numbers|
|secrets.randbelow(10)|	Returns a secure random number|

- Use randint() when you want to generate a random number from an inclusive range.
- Use randrange() when you want to generate a random number within a range by specifying the increment. It produces a random number from an exclusive range.

In [4]:
# random integer from 0 to 9
num1 = random.randint(0, 9)
print(num1)

# Random integer from 10 to 100
num2 = random.randint(10, 100)
print(num2)


# random number of length 4
num1 = random.randint(1000, 9999)
print(num1)

# random number of length 4 with step 2
num2 = random.randrange(1000, 10000, 2)
print(num1, num2)

# negative integer
singed_int = random.randrange(-60, -6)
print(singed_int)

for i in range(5):
    print(random.randint(-10, 10), end=' ')

print('\n\n')
num = random.choice([-1, 1])
print(num)

1
27
5645
5645 4098
-28
1 -6 9 8 -10 


-1


In [5]:
# Generate a list of random integer numbers

random_list = []
# Set a length of the list to 10
for i in range(0, 10):
    # any random numbers from 0 to 1000
    random_list.append(random.randint(0, 1000))
print(random_list)


[802, 874, 321, 248, 34, 464, 775, 251, 72, 346]


In [6]:
# Create a list of random numbers without duplicates
# Generate 10 unique random numbers within a range
num_list = random.sample(range(0, 1000), 10)
print(num_list)


[722, 733, 105, 646, 288, 229, 199, 90, 188, 303]


In [7]:
# sort random numbers list

sample_list = random.sample(range(50, 500, 5), 5)
print(sample_list)

sample_list.sort()
print(sample_list)

[120, 285, 250, 195, 410]
[120, 195, 250, 285, 410]


**Generate a secure random integer**
- Above all, examples are not cryptographically secure. The cryptographically secure random generator generates random numbers using synchronization methods to ensure that no two processes can obtain the same number simultaneously.

In [8]:
import secrets

# secure random integer
# from 0 to 10
secure_num = secrets.randbelow(10)
print(secure_num)

0


**Create a multidimensional array of random integers**
- Generate a 4 x 4 array of ints between 10 and 50, exclusive:

In [9]:
import numpy

# 4 x 4 array
newArray = numpy.random.randint(10, 50, size=(4, 4))
print(newArray)

[[43 29 24 33]
 [45 32 45 48]
 [48 37 12 21]
 [27 43 29 36]]


- Generate a 5 x 3 array of random integers between 60 and 100, inclusive.

In [10]:
# 3 x 5 array of ints
newArray = numpy.random.random_integers(60, 100, size=(3, 5))
print(newArray)

[[94 83 76 60 69]
 [75 88 98 91 65]
 [71 89 79 63 74]]


C:\Users\Kwang-Chul Kwon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(60, 100 + 1) instead
  


# random choice() function to select a random item from a List and Set

|Function|	Description|
|:--|:--|
|random.choice(list)|	Choose a random item from a sequence. Here seq can be a list, tuple, string, or any iterable like range.|
|random.choices(list, k=3)	|Choose multiple random items from a list, set, or any data structure.|
|random.choice(range(10, 101))|	Pick a single random number from range 1 to 100|
|random.getrandbits(1)|	Returns a random boolean|
|random.choice(list(dict1))	|Choose a random key from a dictioanry|
|np.random.choice()|Return random choice from a multidimensional array|
|secrets.choice(list1)	|Choose a random item from the list securely|

In [11]:
number_list = [111, 222, 333, 444, 555]
# random item from list
print(random.choice(number_list))

111


In [12]:
movies_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']

# pick a random choice from a list of strings.
movie = random.choice(movies_list)
print(movie)

for i in range(2):
    movie = random.choice(movies_list)
    print(movie)

The Shawshank Redemption
The Godfather
Pulp Fiction


**The choice() function only returns a single item from a list. If you want to select more than one item from a list or set, use random sample() or choices() instead.**
- The random.choices() method was introduced in Python version 3.6, and it can repeat the elements. It is a random sample with a <p style='color:red'>**replacement.**</p>
- Using the random.choices(k) method we can specify the sampling size.

In [13]:
# sampling with replacement
original_list = [20, 30, 40, 50, 60, 70, 80]
# k = number of items to select
sample_list = random.choices(original_list, k=3)
print(sample_list)

[70, 80, 40]


**Random choices without repetition**
- Use the **random.sample()** function when you want to choose multiple random items from a list\without repetition or duplicates.

- The choices() was added in Python 3.6 to choose n elements from the list randomly, but this function can repeat items.
- The choices() function is mainly used to implement **weighted** random choices to choose multiple elements from the list with different probabilities.

**So we can’t choose random items directly from a set without copying them into a tuple.**

To choose a random item from a set, first, copy it into a tuple and then pass the tuple to the choice() function

In [14]:
sample_set = {20, 35, 45, 65, 82}
item = random.choice(tuple(sample_set))
# random item from set
print(item)

65


In [15]:
# Choose randomly number from range of 10 to 100
num = random.choice(range(10, 101))
print(num)

res = random.choice([True, False])
print(res)


66
True


In [16]:
# Also, you can use the random.getrandbits() to generate random Boolean in Python fastly and efficiently.
# get random boolean
res = random.getrandbits(1)
print(bool(res))

False


In [17]:
atuple = (20, 30, 4)
# Random choice from a tuple
num = random.choice(atuple)
print(num)

4


In [18]:
weight_dict = {
    "Kelly": 50,
    "Red": 68,
    "Scott": 70,
    "Emma": 40
}
# random key
key = random.choice(list(weight_dict))
# fetch value using key name
print("Random key-value pair is ", key, ":", weight_dict[key])

Random key-value pair is  Red : 68


In [19]:
movie_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']

# get random index number
i = random.randrange(len(movie_list))
item = movie_list[i]
# Select item using index number
print("Randomly selected item", movie_list[i], "is present at index:", i)

Randomly selected item The Godfather is present at index: 0


**Pick a random value from multiple lists with equal probability**

In [20]:
list_one = ["Thomas", "Liam", "William"]
list_two = ["Emma", "Olivia", "Isabella"]

seqs = list_one, list_two
print(seqs)
print(list(map(len, seqs)))
print(random.choices(seqs, weights=map(len, seqs)))

# Random item  from two lists
item = random.choice(random.choices(seqs, weights=map(len, seqs))[0]) # [0] is because double bracket
print(item)

(['Thomas', 'Liam', 'William'], ['Emma', 'Olivia', 'Isabella'])
[3, 3]
[['Thomas', 'Liam', 'William']]
Olivia


**Choose a random element from a multidimensional array**

In [21]:
import numpy as np

array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing 2D Array")
print(array, end='\n\n')

print("Choose random row from a 2D array")
randomRow = np.random.randint(3, size=1)
print(randomRow)
print(array[randomRow[0], :])
print(array[randomRow[0]], end='\n\n')

print("Random item from random row is")
print(np.random.choice(array[randomRow[0], :]))

Printing 2D Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Choose random row from a 2D array
[0]
[11 22 33]
[11 22 33]

Random item from random row is
22


In [22]:
array = [10, 20, 30, 40, 50, 20, 40]

x = np.random.choice(array, size=1)
print("single random choice from 1-D array", x)

items = np.random.choice(array, size=3, replace=False)
print("multiple random choice from numpy 1-D array without replacement ", items)

choices = np.random.choice(array, size=3, replace=True)
print("multiple random choices from numpy 1-D array with replacement ", choices)

single random choice from 1-D array [30]
multiple random choice from numpy 1-D array without replacement  [50 20 20]
multiple random choices from numpy 1-D array with replacement  [20 50 40]


**Secure random choice**
- Note: Above all, examples are not cryptographically secure. If you are using it to pick a random item inside any security-sensitive application, then secure your random generator and use random.SystemRandom().choice() instead of random.choice().

In [23]:
movie_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']
# secure random generator
secure_random = random.SystemRandom()
item = secure_random.choice(movie_list)
print (item)

The Wizard of Oz


**Randomly choose the same element from the list every time**

In [24]:
float_list = [22.5, 45.5, 88.5, 92.5, 55.4]
for i in range(5):
    # seed the random number generator
    random.seed(4)
    # print random item
    print(random.choice(float_list))

45.5
45.5
45.5
45.5
45.5


**Randomly choose an object from the List of Custom Class Objects**

In [25]:
# custom class
class studentData:
    def __init__(self, name, age):
        self.name = name
        self.age = age


jhon = studentData("John", 18)
emma = studentData("Emma", 19)

object_list = [jhon, emma]

# pick list index randomly using randint()
i = random.randint(0, len(object_list) - 1)
# Randomly select object from the given list of custom class objects
obj = object_list[i]
print(obj.name, obj.age)

Emma 19


# random.sample()

|Operation|	Description|
|:--|:--|
|random.sample(seq, n)|	Generate n unique samples (multiple items) from a sequence without repetition. Here, A seq can be a list, set, string, tuple. Sample without replacement.
|random.choices(seq, n)|	Generate n samples from a sequence with the possibility of repetition. Sample with replacement|
|random.sample(range(100), 5)|	Return the sampled list of unique random integers.|
|random.sample(d1.items(), 2)|	Returns two key-value pairs from Python dictionary.|

In [26]:
aList = [20, 40, 80, 100, 120]
sampled_list = random.sample(aList, 3)
print(sampled_list)
print()

names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]
# choose three random sample with replacement to including repetition
sample_list3 = random.choices(names, k=3)
print(sample_list3)

[20, 100, 40]

['Nadal', 'Roger', 'Novac']


In [29]:
# create list of 5 random numbers
num_list = random.sample(range(100), 5)
print(num_list)
print()

# create list of 5 numbers
num_list = random.sample(range(100), 10)
random.shuffle(num_list)
print(num_list)
print()

aSet = {"Jhon", "kelly", "Scoot", "Emma", "Eric"}
# random 3 samples from set
sampled_set = random.sample(aSet, 3)
print(sampled_set)
print()

marks_dict = {
    "Kelly": 55,
    "jhon": 70,
    "Donald": 60,
    "Lennin": 50
}
sampled_dict = random.sample(marks_dict.items(), 2)
print(sampled_dict)

# Access key-value from sample
# First key:value
print(sampled_dict[0][0], sampled_dict[0][1])

# Second key:value
print(sampled_dict[1][0], sampled_dict[1][1])

[68, 82, 60, 89, 43]

[35, 8, 18, 25, 86, 52, 56, 23, 80, 81]

['Jhon', 'kelly', 'Eric']

[('jhon', 70), ('Kelly', 55)]
jhon 70
Kelly 55


In [30]:
# Randomly select same sample list every time
alist = [20.5, 40.5, 30.5, 50.5, 70.5]

for i in range(3):
    # use 4 as a seed value
    random.seed(4)
    # get sample list of three item
    sample_list = random.sample(alist, 3)
    print(sample_list)

[40.5, 30.5, 20.5]
[40.5, 30.5, 20.5]
[40.5, 30.5, 20.5]


In [31]:
array = numpy.array([[2, 4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]])
print("Printing 2D Array")
print(array)

print("Choose 3 sample rows from 2D array")
randomRows = numpy.random.randint(5, size=2)
for i in randomRows:
    print(array[i, :])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Choose 3 sample rows from 2D array
[ 6 12 18]
[2 4 6]


# weighted random choices

In [32]:
sampleList = [10, 20, 30, 40]
x = random.choice(sampleList)
print(x)
print()

numberList = [111, 222, 333, 444, 555]
print(random.choices(numberList, weights=(10, 20, 30, 40, 50), k=5))
print()

nameList = ["Kelly", "Scott", "Emma", "Jon"]
print(random.choices(nameList, cum_weights=(5, 15, 30, 50), k=4))

40

[444, 222, 111, 444, 333]

['Jon', 'Kelly', 'Emma', 'Emma']


**Choose a single element form list with different probability**

In [33]:
names = ["Kelly", "Scott", "Emma", "Jon"]
for i in range(3):
    item = random.choices(names, cum_weights=(5, 15, 30, 50), k=1)
    print(item)
    print("Iteration:", i, "Weighted Random choice is", item[0])
    print()

['Jon']
Iteration: 0 Weighted Random choice is Jon

['Jon']
Iteration: 1 Weighted Random choice is Jon

['Scott']
Iteration: 2 Weighted Random choice is Scott



**Probability of getting 6 or more heads from 10 spins**

In [34]:
# we specified head and tail of a coin in string
coin = "HT"
# Execute 3 times to verify we are getting 6 or more heads in every 10 spins
for i in range(3):
    print(random.choices(coin, cum_weights=(0.61, 1.00), k=10))

['T', 'H', 'T', 'H', 'H', 'H', 'H', 'T', 'T', 'T']
['H', 'T', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'T']
['T', 'H', 'H', 'T', 'H', 'T', 'H', 'H', 'H', 'H']


**Generate weighted random numbers**

In [35]:
# Generate 6 random numbers from a given range with weighted probability
numbers = random.choices(range(10, 40, 5), cum_weights=(5, 15, 10, 25, 40, 65), k=6)
print(numbers)

[25, 25, 35, 15, 30, 35]


**Numpy’s random.choice() to choose elements from the list with different probability**
```python
numpy.random.choice(a, size=None, replace=True, p=None)
```

In [36]:
numberList = [100, 200, 300, 400]
# Choose elements with different probabilities
sampleNumbers = np.random.choice(numberList, 4, p=[0.10, 0.20, 0.30, 0.40])
print(sampleNumbers)

[400 200 100 300]


# random.seed() function to initialize the pseudo-random number generator

In [37]:
print('Random number with seed 30')
for i in range(3):
    # Random number with seed 30
    random.seed(30)
    print(random.randint(25, 50))

Random number with seed 30
42
42
42


In [38]:
random.seed(30)
print("first Number", random.randint(25, 50))

# generates a different random number
print("Second Number ", random.randint(25, 50))

# will generate a same random number as first one because seed value is same
random.seed(30)
print("Third Number", random.randint(25, 50))

first Number 42
Second Number  50
Third Number 42


**Set system time as a seed value instead of OS-specific randomness source**

In [39]:
from datetime import datetime

# Random number with system time
random.seed(datetime.now())
print("Random Number", random.randint(25, 50))

Random Number 26



**Get a seed value used by a random generator**

In [40]:
import sys

# create a seed
seed_value = random.randrange(sys.maxsize)
# save this seed somewhere. So if you like the result you can use this seed to reproduce it
print('Seed value:', seed_value)


# Now, Seed the random number generator
random.seed(seed_value)
num = random.randint(10, 500)
print("Random Number", num)

Seed value: 5380278777295329594
Random Number 392


In [41]:
# Random seed with randrange
random.seed(350)
print(random.randrange(300, 500))
# output 336

random.seed(350)
print(random.randrange(300, 500))

names = ["Alex", "Emma", "Kelly", "Scott", "Jessa"]
random.seed(50)
random_item = random.choice(names)
print ("First random name from list ", random_item)

random.seed(50)
random_item = random.choice(names)
print ("Second random name from list ", random_item)

# using random.seed() and random.sample() together
fruit_list = ["Apple", "Mango", "Banana", "Apricot", "Cherries", "Grape", "Kiwi"]

random.seed(3)
sample_list = random.sample(fruit_list, 3)
print("First sample fruit list ", sample_list)

random.seed(3)
sample_list = random.sample(fruit_list, 3)
print("Second sample fruit list ", sample_list)

numbers = [10, 20, 30, 40, 50, 60]
print("Original list: ", numbers)
random.seed(4)
random.shuffle(numbers)
print("Shuffled list ", numbers)

random.seed(4)
random.shuffle(numbers)
print("Reshuffled list ", numbers)

392
392
First random name from list  Scott
Second random name from list  Scott
First sample fruit list  ['Mango', 'Cherries', 'Grape']
Second sample fruit list  ['Mango', 'Cherries', 'Grape']
Original list:  [10, 20, 30, 40, 50, 60]
Shuffled list  [40, 60, 50, 10, 30, 20]
Reshuffled list  [10, 20, 30, 40, 50, 60]


- https://pynative.com/python-random-sample/

In [42]:
num_list = random.sample(range(100), 5)
print(num_list)

[61, 19, 11, 8, 2]


In [43]:
marks_dict = {
    "Kelly": 55,
    "jhon": 70,
    "Donald": 60,
    "Lennin": 50
}
sampled_dict = random.sample(marks_dict.items(), 2)
print(sampled_dict)
# Output [('Donald', 60), ('jhon', 70)]

# Access key-value from sample
# First key:value
print(sampled_dict[0][0], sampled_dict[0][1])
# Output jhon 70

# Second key:value
print(sampled_dict[1][0], sampled_dict[1][1])
# output Kelly 55

[('Lennin', 50), ('Donald', 60)]
Lennin 50
Donald 60


In [44]:
# Get a sample array from a multidimensional array

import numpy

array = numpy.array([[2, 4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]])
print("Printing 2D Array")
print(array)

print("Choose 3 sample rows from 2D array")
randomRows = numpy.random.randint(5, size=2)
for i in randomRows:
    print(array[i, :])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Choose 3 sample rows from 2D array
[ 5 10 15]
[ 5 10 15]


- ```python
random.choices(population, weights=None, *, cum_weights=None, k=1)
```

# random.shuffle() function to shuffle list

|Function|Description|
|:--|:--|
|random.shuffle(list1)|Shuffle list in-place (preferred way)|
|random.sample(seq, len(seq))|Shuffle list not in place to return a new shuffled list. (non-preferred way) OR
To shuffle an immutable sequence such as string or range.|
|np.random.shuffle(array)|Shuffling multidimensional array|


In [45]:
import random

number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
# Original list
print(number_list)

# List after first shuffle
random.shuffle(number_list)
print(number_list)

# List after second shuffle
random.shuffle(number_list)
print(number_list)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
[14, 56, 63, 42, 21, 49, 70, 28, 7, 35]
[56, 7, 28, 35, 63, 49, 70, 14, 42, 21]


**Randomly Shuffle Not in Place**

In [46]:
# Option 1: Make a Copy of the Original List

numbers = [33, 66, 99, 188, 256, 412, 748]
# copy to new list
new_list = numbers.copy()
# shuffle the new list
random.shuffle(new_list)

print("Original list : ", numbers)
print("List after shuffle", new_list)

Original list :  [33, 66, 99, 188, 256, 412, 748]
List after shuffle [188, 66, 256, 33, 412, 748, 99]


In [47]:
# Option 2: Shuffle list not in Place using random.sample()

import random

# custom class
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

emp1 = Employee("Kelly", 10000)
emp2 = Employee("Abigail", 8000)
emp3 = Employee("Sampson", 12000)
emp4 = Employee("Joe", 7000)

# list with 4 objects
emp_list = [emp1, emp2, emp3, emp4]

# print original list
for emp in emp_list:
    print(emp.name, emp.salary, end=', ')

# shuffle list of objects
# sample size (k) = length of a list
shuffledList = random.sample(emp_list, k=len(emp_list))
print("\nPrinting new shuffled list of employee object")

for emp in shuffledList:
    print(emp.name, emp.salary, end=', ')

Kelly 10000, Abigail 8000, Sampson 12000, Joe 7000, 
Printing new shuffled list of employee object
Joe 7000, Sampson 12000, Kelly 10000, Abigail 8000, 

**Shuffle Two Lists At Once With Same Order**

In [48]:
import random

# list of names
employees = ['Jon', 'Emma', 'Kelly', 'Jason']
# list of numbers
salary = [7000, 6500, 9000, 10000]

# Lists before Shuffling
print("Employee Names: ", employees)
print("Employee Salaries: ", salary)


# To Shuffle two List at once with the same order
mapIndexPosition = list(zip(employees, salary))
print(mapIndexPosition)
print()
random.shuffle(mapIndexPosition)

# make list separate
list1_names, list2_salary = zip(*mapIndexPosition) # unpack first and then zip

# Lists after Shuffling
print("Employee Names: ", list1_names)
print("Employee Salary: ", list2_salary)


# Employee name and salary present index 3
print(list1_names[3], list2_salary[3])


Employee Names:  ['Jon', 'Emma', 'Kelly', 'Jason']
Employee Salaries:  [7000, 6500, 9000, 10000]
[('Jon', 7000), ('Emma', 6500), ('Kelly', 9000), ('Jason', 10000)]

Employee Names:  ('Jon', 'Kelly', 'Jason', 'Emma')
Employee Salary:  (7000, 9000, 10000, 6500)
Emma 6500


**Shuffling NumPy Multidimensional Array**

In [49]:
import numpy as np

print('Before shuffling 2dimensional array')
sample_array = np.arange(100, 240, 10)
sample_array = sample_array.reshape(7, 2)
print(sample_array)

print('After shuffling 2dimensional array')
np.random.shuffle(sample_array)
print(sample_array)

Before shuffling 2dimensional array
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]
 [200 210]
 [220 230]]
After shuffling 2dimensional array
[[220 230]
 [140 150]
 [160 170]
 [200 210]
 [100 110]
 [120 130]
 [180 190]]


**Shuffle a List to Get the Same Result Every time**

In [50]:
import random

numbers = [10, 20, 30, 40, 50, 60]
print("Original list: ", numbers)

# shuffle 8 times
for i in range(8):
    # seed PRNG
    random.seed(9)
    # shuffle list
    random.shuffle(numbers)
    print(f"result list {i+1} ", numbers)

Original list:  [10, 20, 30, 40, 50, 60]
result list 1  [60, 10, 20, 30, 50, 40]
result list 2  [40, 60, 10, 20, 50, 30]
result list 3  [30, 40, 60, 10, 50, 20]
result list 4  [20, 30, 40, 60, 50, 10]
result list 5  [10, 20, 30, 40, 50, 60]
result list 6  [60, 10, 20, 30, 50, 40]
result list 7  [40, 60, 10, 20, 50, 30]
result list 8  [30, 40, 60, 10, 50, 20]


**Shuffle a String**

In [53]:
string_one = "PYnative"
shuffled=random.shuffle(string_one)
print(shuffled)

TypeError: 'str' object does not support item assignment

**Shuffle a String by Converting it to a List**

In [54]:
import random

sample_str = "PYnative"
# Original string
print(sample_str)

# convert string into list
char_list = list(sample_str)
print(char_list)

# shuffle list
random.shuffle(char_list)

# convert list to string
final_str = ''.join(char_list)

# shuffled list
print(final_str)

PYnative
['P', 'Y', 'n', 'a', 't', 'i', 'v', 'e']
aYvinPte


**Approach Two: Shuffling a String, not in place**

In [55]:
import random

sample_str = "PYnative"
print(sample_str)

# shuffle string using random.sample()
final_str = ''.join(random.sample(sample_str, len(sample_str)))
print(final_str)

PYnative
niavYPet


### Shuffle Range of Integers

In [56]:
# Shuffle a range of numbers
numbers = list(range(10))
random.shuffle(numbers)
print(numbers)

[8, 4, 7, 0, 3, 5, 6, 9, 2, 1]


### Shuffle a Dictionary in Python

In [57]:
student_dict = {'Eric': 80, 'Scott': 75, 'Jessa': 95, 'Mike': 66}
print("Dictionary Before Shuffling")
print(student_dict)
keys = list(student_dict.keys())
random.shuffle(keys)

ShuffledStudentDict = dict()
for key in keys:
    ShuffledStudentDict.update({key: student_dict[key]})

print("\nDictionary after Shuffling")
print(ShuffledStudentDict)

Dictionary Before Shuffling
{'Eric': 80, 'Scott': 75, 'Jessa': 95, 'Mike': 66}

Dictionary after Shuffling
{'Eric': 80, 'Mike': 66, 'Jessa': 95, 'Scott': 75}


### Shuffle a Python generator

In [58]:
import random

def sample_generator():
    yield 25
    yield 50
    yield 75
    yield 100

print("Generator")
for i in sample_generator():
    print(i, end=", ")
print()
# Shuffle generator
newList = list(sample_generator())
random.shuffle(newList)
print(newList)

print("\nPrint shuffled generator")
for i in newList:
    print(i, end=", ")

Generator
25, 50, 75, 100, 
[75, 100, 50, 25]

Print shuffled generator
75, 100, 50, 25, 

# Generate Random Strings and Passwords

|Constant| Description|
|:--|:--|
|ascii_lowercase	|Contain all lowercase letters|
|ascii_uppercase|Contain all uppercase letters|
|ascii_letters	|Contain both lowercase and uppercase letters|
|digits|Contain digits ‘0123456789’.|
|punctuation	|All special symbols !”#$%&'()*+,-./:;<=>?@[\]^_`{|}~.|
|whitespace	|Includes the characters space, tab, linefeed, return, formfeed, and vertical tab [^ \t\n\x0b\r\f]|
|printable|characters that are considered printable. This is a combination of constants digits, letters, punctuation, and whitespace |

In [59]:
import random
import string

def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    print("Random string of length", length, "is:", result_str)

get_random_string(8)
get_random_string(6)
get_random_string(4)

Random string of length 8 is: mikzbgwa
Random string of length 6 is: nbmpea
Random string of length 4 is: hnxd


In [60]:
import random
import string

def get_random_string(length):
    # With combination of lower and upper case
    result_str = ''.join(random.choice(string.ascii_letters) for i in range(length))
    # print random string
    print(result_str)

# string of length 8
get_random_string(8)
get_random_string(8)

MahWLmmv
afiIbGfK


In [61]:
# Random string of specific letters
import random

# Random string of length 5
result_str = ''.join((random.choice('abcdxyzpqr') for i in range(5)))
print(result_str)

pqdzb


In [62]:
# Random String without Repeating Characters
import random
import string

for i in range(3):
    # get random string of length 8 without repeating letters
    result_str = ''.join(random.sample(string.ascii_lowercase, 8))
    print(result_str)

mgucsefb
birvteys
bdwmhftq


In [63]:
# Create Random Password with Special characters, letters, and digits

import random
import string

# get random password pf length 8 with letters, digits, and symbols
characters = string.ascii_letters + string.digits + string.punctuation
password = ''.join(random.choice(characters) for i in range(8))
print("Random password is:", password)
print()

password = ''.join(random.choice(string.printable) for i in range(8))
print("Random password is:", password)

Random password is: fU]%.+_l

Random password is: Ie-KVqPp


In [64]:
# Random password with a fixed count of letters, digits, and symbols
import random
import string

def get_random_password():
    random_source = string.ascii_letters + string.digits + string.punctuation
    # select 1 lowercase
    password = random.choice(string.ascii_lowercase)
    # select 1 uppercase
    password += random.choice(string.ascii_uppercase)
    # select 1 digit
    password += random.choice(string.digits)
    # select 1 special symbol
    password += random.choice(string.punctuation)

    # generate other characters
    for i in range(6):
        password += random.choice(random_source)

    password_list = list(password)
    # shuffle all characters
    random.SystemRandom().shuffle(password_list)
    password = ''.join(password_list)
    return password

print("First Random Password is ", get_random_password())
print("Second Random Password is ", get_random_password())

First Random Password is  :3Qo0sXa]B
Second Random Password is  K?=Nnl%4Oh


In [65]:
# Generate a secure random string and password
'''Above all, examples are not cryptographically secure. The cryptographically secure 
random generator generates random data using synchronization methods to ensure that no 
two processes can obtain the same data simultaneously.
If you are producing random passwords or strings for a security-sensitive application, 
then you must use this approach.'''

import secrets
import string

# secure random string
secure_str = ''.join((secrets.choice(string.ascii_letters) for i in range(8)))
print(secure_str)

# secure password
password = ''.join((secrets.choice(string.ascii_letters + string.digits + string.punctuation) for i in range(8)))
print(password)

'Above all, examples are not cryptographically secure. The cryptographically secure \nrandom generator generates random data using synchronization methods to ensure that no \ntwo processes can obtain the same data simultaneously.\nIf you are producing random passwords or strings for a security-sensitive application, \nthen you must use this approach.'

FzXbkCKu
MPSjUAZA


In [66]:
# Generate a random alphanumeric string of letters and digits
import random
import string

# get random string of letters and digits
source = string.ascii_letters + string.digits
result_str = ''.join((random.choice(source) for i in range(8)))
print(result_str)

YdbyXJZB


In [67]:
# Random alphanumeric string with a fixed count of letters and digits
import random
import string

def get_string(letters_count, digits_count):
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)
    print('Random string with', letters_count, 'letters', 'and', digits_count, 'digits', 'is:', final_string)

get_string(5, 3)
get_string(6, 2)

Random string with 5 letters and 3 digits is: 1w9Tp6FX
Random string with 6 letters and 2 digits is: k0SqiQ0s


In [68]:
# Generate a random string token
import secrets
print("Secure hexadecimal string token", secrets.token_hex(32)) # get a secure random text in hexadecimal format.

Secure hexadecimal string token bcf8b42c69811d39451cfbbbe889a5368c994e2bf0589b1e60f6a67c5f66c6cc


In [69]:
# Generate universally unique secure random string Id
# The random string generated using a UUID module is suitable for the Cryptographically secure application. 
# The UUID module has various functions to do this. Here in this example, 
# we are using a uuid4() function to generate a random string Id.
import uuid
stringId  = uuid.uuid4()
print("Secure unique string id", stringId)

Secure unique string id 4aed430b-2fe3-4ac7-b461-c19e1014c251


In [70]:
# Use the StringGenerator module to generate a random string

import strgen

random_str = strgen.StringGenerator("[\w\d]{10}").render()
print(random_str)


random_str2 = strgen.StringGenerator("[\d]{3}&[\w]{3}&[\p]{2}").render()
print(random_str2)


2T6BbqISa8
1"7{A3yh


# Random Float numbers in Python using random() and Uniform()

|Function|	Description|
|:--|:--|
|random.random()	|Returns a random float number between 0 and 1|
|random.uniform(10.5, 75.5)	|Returns a random float number between a range|
|round(random.uniform(33.33, 66.66), 2)	|Returns a random float number up to 2 decimal places|
|random.SystemRandom().uniform(5, 10)	|Returns a secure random float number|
|numpy.random.uniform()	|Returns a random array of floats|

In [71]:
import random

x = random.random()
# Random float number
for i in range(3):
    print(random.random())

# Random float number between range 10.5 to 75.5
print(random.uniform(10.5, 75.5))

# between 10 and 100
print(random.uniform(10, 100))

# Random float number with 2 decimal places
print(round(random.random(), 2))
print(round(random.uniform(33.33, 66.66), 2))

# With 1 decimal places
print(round(random.random(), 1))
print(round(random.uniform(33.33, 66.66), 1))


0.20860185315146273
0.3888786457049763
0.6115486771970534
73.31816402014044
41.90779936053554
0.14
52.06
0.1
36.2


**Get random decimal**

To get a random decimal.Decimal instance, you need explicitly convert it into decimal.Decimal.

In [72]:
import random
import decimal

# random decimal
x = decimal.Decimal(str(random.uniform(100, 1000)))
print(x)

600.3637601912715


**Random float number with step**

In [73]:
# random float from 1 to 99.9
int_num = random.choice(range(10, 1000))
float_num = int_num/10
print(float_num)

72.2


**Generate a list of random floats between a range**

In [74]:
import random

random_float_list = []
# Set a length of the list to 10
for i in range(0, 10):
    # any random float between 50.50 to 500.50
    # don't use round() if you need number as it is
    x = round(random.uniform(50.50, 500.50), 2)
    random_float_list.append(x)

print(random_float_list)

[103.57, 239.47, 114.63, 303.37, 408.2, 315.18, 411.74, 348.93, 173.87, 319.28]


**Create a list of unique random float numbers**

In [75]:
# Option 1: Use a list of integers to generate floats.

list_Size = 10
# random float from 1 to 99.9
integer_list = random.sample(range(10, 1000), list_Size)
float_list = [x/10 for x in integer_list]
print(float_list)
print()

# Option 2: Avoid duplicates manually
def get_float_list(start, stop, size):
    result = []
    unique_set = set()
    for i in range(size):
        x = round(random.uniform(start, stop),2)
        while x in unique_set:
            x = round(random.uniform(start, stop),2)
        unique_set.add(x)
        result.append(x)

    return result

print("List of unique random numbers between 100, 1000")
print(get_float_list(100, 1000, 10))

[63.3, 51.6, 36.7, 11.1, 95.5, 5.9, 29.3, 55.1, 14.1, 18.7]

List of unique random numbers between 100, 1000
[818.57, 838.34, 246.0, 810.68, 873.2, 282.6, 526.27, 632.37, 590.96, 174.88]


**Generate a secure random float number**

In [76]:
import random

secure_random = random.SystemRandom()

randomfloat = secure_random.random()
print(randomfloat)

randomfloat = secure_random.uniform(12.5, 77.5)
print(randomfloat)

0.7916511739225813
45.470893732038746


### Use numpy.random to generate an array of random float numbers

In [77]:
import numpy as np

random_float = np.random.randn()
print(random_float)

random_float_number = np.random.uniform(49.5, 99.5)
print(random_float_number)

# Create an n-dimensional array of float numbers

random_float_array = numpy.random.rand(2, 3)
# Random float array 2X3
print(random_float_array,"\n")

#2X2 random float
random_float_array = numpy.random.uniform(75.5, 125.5, size=(2, 2))
print(random_float_array)


1.0699045074288207
56.44994399433493
[[0.54884789 0.5038818  0.5078144 ]
 [0.35668912 0.47818464 0.87288496]] 

[[ 91.40950569 125.47727764]
 [123.6790643  116.47954727]]


# Secrets Module to Generate secure random numbers for managing secrets

The random generator provided by the Python random module is a pseudo-random number generator that is not cryptographically secure. As a result secrets module is added in Python 3.6 and onwards to secure the random number generator.

In [78]:
import secrets

# Getting systemRandom class instance out of secrets module
secretsGenerator = secrets.SystemRandom()

# secure random integer numbers
random_number = secretsGenerator.randint(0, 50)
print(random_number)

# secure random integer number within given
random_number2 = secretsGenerator.randrange(4, 40, 4)
print(random_number2)

# Secure Random choice using secrets
number_list = [6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
secure_choice = secretsGenerator.choice(number_list)
print(secure_choice)

# Secure Random sample
secure_sample = secretsGenerator.sample(number_list, 3)
print(secure_sample)

# Secure Random float number
secure_float = secretsGenerator.uniform(2.5, 25.5)
print(secure_float)

20
36
6
[6, 54, 12]
2.7561443247343664


|Function|	Description|
|:--|:--|
|secrets.SystemRandom()|	Get an instance of the secure random generator|
|secrets.randbelow(n)|	Generate a secure random integer number|
|secrets.choice(seq)|	Returns a secure random element from a non-empty sequence|
|secrets.randbits(k)|	returns a secure unsigned integer with k random bits|
|secrets.token_bytes([nbytes=None])|	Return a secure random byte string|
|secrets.token_hex([nbytes=None])	|Return a secure random text string, in hexadecimal format|
|secrets.token_urlsafe([nbytes=None])|	Return a secure random URL-safe text string|
|secrets.compare_digest(a, b)|	To reduce the risk of timing attacks|

In [79]:
import secrets

# secure Random integer number
for i in range(3):
    print(secrets.randbelow(10), end=', ')
print()

name = "GuidoVanRossum"
# secrets choice from string is
print(secrets.choice(name))

name_list = ["Guido Van Rossum", "Bjarne Stroustrup", "Dennis Ritchie"]
# secure choice from list
print(secrets.choice(name_list))

print()
import secrets

# using 4 bits
print(secrets.randbits(4))

# using 8 bits
print(secrets.randbits(8))

# using 16 bits
print(secrets.randbits(16))

# using 32 bits
print(secrets.randbits(32))

print()

# The secrets module provides functions for generating the secure tokens, 
# useful for applications to generate reset password tokens and hard-to-guess URLs.

# secure byte token
print(secrets.token_bytes(16))

# secure hexadecimal token
print(secrets.token_hex(32))

# generate secure URLs
passwordResetLink = "demo.com/customer/eric/reset="
passwordResetLink += secrets.token_urlsafe(32)
print(passwordResetLink)


1, 3, 0, 
i
Guido Van Rossum

7
132
20051
2238865605

b'k\x15\xd7\x07 \xcc\xdd2\xce_\xeeo?Y\xc1\x9d'
8e56435983657a189c51041a421963cd0b37f4dfdcc7318da1fc395ff797ac16
demo.com/customer/eric/reset=ymTW8o9xewzFNISa9KMRTvCQ5GYGhtpPAN6r9ZNxicI


**Practical Example of secrets module**

In [80]:
import secrets
import string

stringSource = string.ascii_letters + string.digits + string.punctuation
password = secrets.choice(string.ascii_lowercase)
password += secrets.choice(string.ascii_uppercase)
password += secrets.choice(string.digits)
password += secrets.choice(string.punctuation)

for i in range(6):
    password += secrets.choice(stringSource)

char_list = list(password)
secrets.SystemRandom().shuffle(char_list)
password = ''.join(char_list)
print("Secure Password is ", password)

print("Ppassword Reset URL Link")
SecureURL = "https://demo.com/user/jhon/reset="
SecureURL += secrets.token_urlsafe(32)
print(SecureURL)

Secure Password is  v4#y7LZ$tq
Ppassword Reset URL Link
https://demo.com/user/jhon/reset=I4joHa_TXXU5iGe7Wa1lylHCidKad5ILVnUDubNRybw


## **Simulations**


- Six roulete wheel spins (weighted sampling with replacement)

In [81]:
random.choices(['red', 'black', 'green'], [9, 9, 1], k=6)

['black', 'black', 'red', 'red', 'black', 'black']

- Deal 20 cards without replacement from a deck of 52 playing cards, and determine the proportion of cards with a ten\-value:  ten, jack, queen, or king.


In [101]:
tens=['tens']*16
low_cards=['low cards']*36
total_sample=tens+low_cards

dealt=random.sample(total_sample, k=20)

cnt=dealt.count('tens')
cnt=cnt/20
print(cnt)

0.4


In [105]:
# choices does random sampling with a replacement
dealt=random.choices(['tens', 'low cards'], [16, 36], k=20)
dealt.count('tens')/20

0.2

- Estimate the probability of getting 5 or more heads from 7 spins  of a biased coin that settles on heads 60% of the time.

In [124]:
def trial():
    return random.choices('HT', cum_weights=(0.6, 1), k=7).count('H')>=5

print(sum(trial() for i in range(10000))/10000)

0.4213


- Probability of the median of 5 samples being in middle two quartiles

In [133]:
def trial():
    return 2_500 <= sorted(random.choices(range(10_000), k=5))[2] < 7_500

print(sum(trial() for i in range(10_000))/10000)

0.7912


In [132]:
sorted(random.choices(range(10_000), k=5))[2]

5214

- Example of statistical bootstrapping using resampling with replacement to estimate a confidence interval for the mean of a sample:

In [12]:

from statistics import mean
import random

data = [41, 50, 29, 37, 81, 30, 73, 63, 20, 35, 68, 22, 60, 31, 95]
means = sorted(mean(random.choices(data, k=len(data))) for i in range(100))
# print(means)
print(f'The sample mean of {mean(data):.1f} has a 90% confidence '
      f'interval from {means[5]:.1f} to {means[94]:.1f}')

The sample mean of 49.0 has a 90% confidence interval from 40.1 to 59.9


* Example of a resampling permutation test to determine the statistical significance or p-value of an observed difference between the effects of a drug versus a placebo:

In [25]:
from statistics import mean
import random

drug = [54, 73, 53, 70, 73, 68, 52, 65, 65]
placebo = [54, 51, 58, 44, 55, 52, 42, 47, 58, 46]
observed_diff = mean(drug) - mean(placebo)
combined = drug + placebo

n = 10_000
count = 0
combined = drug + placebo
for i in range(n):
    random.shuffle(combined)
    new_diff = mean(combined[:len(drug)]) - mean(combined[len(drug):])
    count += (new_diff >= observed_diff)

print(f'{n} label reshufflings produced only {count} instances with a difference')
print(f'at least as extreme as the observed difference of {observed_diff:.1f}.')
print(f'The one-sided p-value of {count / n:.4f} leads us to reject the null')
print(f'hypothesis that there is no difference between the drug and the placebo.')

[54, 73, 53, 70, 73, 68, 52, 65, 65, 54, 51, 58, 44, 55, 52, 42, 47, 58, 46]
[73, 44, 55, 70, 58, 52, 68, 65, 47, 42, 53, 65, 54, 58, 54, 46, 52, 73, 51]
10000 label reshufflings produced only 12 instances with a difference
at least as extreme as the observed difference of 13.0.
The one-sided p-value of 0.0012 leads us to reject the null
hypothesis that there is no difference between the drug and the placebo.
